language: swift
os: osx
osx_image: xcode11.5

branches:
  except: /^feature\//

script:
  - swift test -v

stages:
  - Lint
  - Tests

jobs:
  include:
    - stage: Lint
      name: Lint
      git:
        depth: 1
        submodules: false
      cache:
        - directories:
          - /usr/local/lib/mint
      install: 
        - brew install mint
        - mint install -n SwiftLint
      script: mint run SwiftLint swiftlint lint --reporter emoji

    - stage: Tests
      osx_image: xcode11.5
    
  fast_finish: true

notifications:
  email: false
  slack:
    rooms:
      secure: jdNxhu4I613D2/LB95QEEVAG/BqSHbqi5HMuvc8+ys3J1lO0wK9z67zYBhCLuUlw3ZdTiecPpteOiwc0N8RTL+lKJzgAtU+xzVn9u6qS+GvIn2hBuy8+GixUNX6sM75B1FsdD7FxAcc04u8KoJjgp5wRVL7XbCvYDoMqq9BR5KXfkJXFNnBUmnSPGyHD6dYV0obdjrI+3ORLSL+b+K0JAI1+rMSxg9P9aj34JrLpoKZRmffEytu5zkeKmvkRsI//uZt8HkYnHpadCq0pRLLw0HKLL+b6ukRYy6C1c4bstGhvuKMXoPQrp5Rz1SKGlVUDdEqIueeCOKKC1DdAziYU4zlx+bFt7yyvQx0CFCKZ8qHYZYQjMdLyD0m7Z2ekzCzy0jMOPGd8gHydC6JMtoSeMU9OCyHUAJ1OhAlcXOS9Dw9kzMfGgTF2cJx3lPycOzE045rzCwDvHA2CH41HA/YskFA51d19xIXFnqDtke6GoChOAIshAbWFh8ep+c+AXqCZagAumx/0nAHfeDyQWPABti+8rv/O5D3IgdfX0vOaW+skec3VlIvvIB7KuaDvzzdXMh1mc784Q8NwafJ9TIA5YhcMqB9PmGBxaKlM+AeNa8Yx+SfhpoB/bX6WOSyPiuIkEj0lLdzXWL6ag9gX1Jc252XqVgMub9CqO1sWSb3UO4M=
    on_success: change
