language: swift
os: osx
osx_image: xcode11.4

branches:
  except: /^feature\//

script:
  - swift test -v

stages:
  - Lint
  - Tests

jobs:
  include:
    - stage: Lint
      name: Lint
      git:
        depth: 1
        submodules: false
      cache:
        - directories:
          - /usr/local/lib/mint
      install: 
        - brew install mint
        - mint install -n SwiftLint
      script: mint run SwiftLint swiftlint lint --reporter emoji

    - stage: Tests
      osx_image: xcode11.3
    - stage: Tests
      osx_image: xcode11.4
    
  fast_finish: true

notifications:
  email: false
  slack:
    rooms:
      secure: DDi9XmIjz7/npRlFtczpFCdPLYkt/aFKzUPBqWXRE3AMp0LXKk+gsDQBgURNZ/BoQpfRpPJiLtcTm/CjdhtWxbrlu7BS8bt4UxghIF/GiZqRTGiZgb4NHqofr5EFbUpHvg+pkFrEl5UvABhqx206FzCUOBZoE76H3ImJSqO0nmF1kk1ls8h7C08uEwgeOa151511pUfrS0Qquu1qjngUabOT7Bzl82/AcJ6eG+6C8P0Sj94+sJkuSKrQXAFcvYrM0j4VcZyRrjJrDWDgD4L5qBzvxRojZlU2puuFZ/QVEGJAqQn+M8I94fP52fZmMzap/276Pl1eHpUS2mDsUtcnNeH3slavcirLePe9rNBvyNSY63qn021aPwKOy/xcsZdUYkNxkty4ldTod/B0GT15aXXc70KIpPNe17+h+zebNeMjsipRQxNTN9tnLfJqpMN2ZtjwSTELoXtAW6CGNrR/S4XzZ1WJEpC1qoqYVaiVs1Du2W5/h4oPaZ59T0Q68Kp2eNm4MyH+ImVQV0xW/nN74eZHtVFbdtjk3MoGxA6mfupeZbvhdQ4OAIUicouPVoA61lBjFOBZUtNQr9YEpNltADmnFocAMo/0C7HPseb5uRku9O0zefjSHxii20eJ8+FuHBVXWDj61jnTUhXqxtDNWdOJ7nPIuYhqNqtp6/vVylA=
    on_success: change
